# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: ContentaSoft.VideoRecompressStudio
PackageVersion: 2026.2.22
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- Publisher: Contenta Software
  ProductCode: '{B4C8F5E3-AD2E-5F9B-C3F6-8E4B0G7D1F25}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://www.contenta-software.com/VideoRecompressStudioPremium2026-Setup-2026.2.22.exe
  InstallerSha256: 60025FD8BF7A9584D3B25F968A0D7A52974AC5BEAE02ACEDFFA0644ABB542EA0
ManifestType: installer
ManifestVersion: 1.12.0