# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: ContentaSoft.CadConverter
PackageVersion: 1.0.27
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- Publisher: Contenta Software
  ProductCode: '{B4C8E5F3-0D2E-5F9B-C3F6-8E4B0A7D1F25}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://www.contenta-software.com/CadConverterPremium2026-Setup-1.0.27.exe
  InstallerSha256: CEA15ECDF3193BD51C13A4FBF0678E404FD2999CD2493DDDF94E4AE9C2ABDD59
ManifestType: installer
ManifestVersion: 1.12.0