# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ContentaSoft.AIVideoEnhancerStudio
PackageVersion: 2026.7.15
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- Publisher: Contenta Software
  ProductCode: '{C5D9F7E4-BE3F-6A0C-D4G7-9F5C1H8E2G36}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://www.contenta-software.com/AIVideoEnhancerStudioPremium2026-Setup-2026.7.15.exe
  InstallerSha256: AF16E5FE3FE8A8CAABABD8B822F5106515777F5629F63AC51EAA7352988CAC91
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
