# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ContentaSoft.VideoRecompressStudio
PackageVersion: 2026.2.20
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- Publisher: Contenta Software
  DisplayVersion: 2026.2.20
  ProductCode: '{B4C8F5E3-AD2E-5F9B-C3F6-8E4B0G7D1F25}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://www.contenta-software.com/VideoRecompressStudioPremium2026-Setup-2026.2.20.exe
  InstallerSha256: A8017CFA916FB7338454F3A3EBD0721280DE31CBF99756A5E7678D262F35748F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
